
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Disclaimer | Niche Finder',
  description: 'Important disclaimers regarding the use of Niche Finder and its AI-generated outputs.',
};

export default function DisclaimerPage() {
  return (
    <article className="prose prose-invert prose-lg max-w-4xl mx-auto prose-headings:text-foreground prose-a:text-primary hover:prose-a:text-primary/80 prose-strong:text-foreground">
      <h1>Disclaimer</h1>
      <p className="text-muted-foreground">Last updated: 17th May 2026</p>
      <p className="lead">
        The information provided by Niche Finder Ltd. ("we," "us," or "our") on this platform is for general informational and educational purposes only. All information, analysis, and AI-generated content is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding its accuracy, adequacy, validity, reliability, or completeness.
      </p>

      <section>
        <h2>1. Not Professional Advice</h2>
        <p>
          The content, scores, reports, financial models, and all other data generated by our platform, including through the use of Artificial Intelligence (collectively, the "Outputs"), are not intended to be, and should not be construed as, professional business, financial, investment, legal, or tax advice. The Platform is an informational tool, not a licensed professional advisor.
        </p>
      </section>

      <section>
        <h2>2. No Guarantee of Accuracy, Success or Profitability</h2>
        <p>
          While we strive to provide high-quality information, we do not guarantee the accuracy, completeness, or timeliness of the Outputs. The business world is dynamic and subject to unforeseeable changes. Niche Finder does not warrant or guarantee any specific business outcome, including but not limited to profitability, fundability, market success, or compliance with regulations.
        </p>
      </section>

      <section>
        <h2>3. Your Responsibility to Verify and Conduct Due Diligence</h2>
        <p>
          <strong>Your use of the Platform and your reliance on any information or AI-generated Outputs is solely at your own risk.</strong> It is your critical responsibility to:
        </p>
        <ul>
            <li>Conduct your own independent and thorough due diligence on any business idea or market.</li>
            <li>Independently verify all data, figures, and assumptions provided by the Platform.</li>
            <li>Consult with qualified and licensed professional advisors (such as lawyers, accountants, and business consultants) before making any business or financial decisions.</li>
        </ul>
        <p>
            Do not rely solely on the information provided by our platform to make any decision of financial or legal consequence.
        </p>
      </section>

      <section>
        <h2>4. AI and Automation Disclaimer</h2>
        <p>
          Our platform utilises advanced Artificial Intelligence. You must understand and acknowledge that AI outputs are probabilistic and based on the data and models available at the time of generation. As such, AI-generated content may be incomplete, contain inaccuracies, be based on outdated information, or fail to consider the full context of your specific situation. AI is a tool to augment human intelligence, not replace it.
        </p>
      </section>

      <section>
        <h2>5. No Fiduciary Relationship</h2>
        <p>
          Your use of the Platform does not create a fiduciary, advisory, or professional-client relationship of any kind between you and Niche Finder Ltd.
        </p>
      </section>
      
      <section>
        <h2>6. Limitation of Liability</h2>
        <p>
            Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Platform or reliance on any information provided. This includes, but is not limited to, lost profits, lost revenue, lost data, or any other commercial damages. For further details, please see the Limitation of Liability section in our <Link href="/terms">Terms of Use</Link>.
        </p>
      </section>

       <section>
        <h2>Contact Us</h2>
        <p>If you have any questions about this Disclaimer, please contact us at <a href="mailto:support@nichefinder.io">support@nichefinder.io</a>.</p>
      </section>
    </article>
  );
}
